INSERT INTO SECURITY_PERMISSION VALUES (200,'SEED',NOW(),0,NULL,NULL,0,'Permission for Library Admin','ROLE_LIBADMIN');

INSERT INTO SECURITY_PERMISSION VALUES (300,'SEED',NOW(),0,NULL,NULL,0,'Permission for Library Member','ROLE_LIBMEMBER');

INSERT INTO SECURITY_GROUP VALUES(200,'SEED',NOW(),0,NULL,NULL,0,'LIBADMIN','1');

INSERT INTO SECURITY_GROUP VALUES(300,'SEED',NOW(),0,NULL,NULL,0,'LIBMEMBER','2');

INSERT INTO SECURITYGROUP_SECURITY_PERMISSIONS VALUES (200,200);

INSERT INTO SECURITYGROUP_SECURITY_PERMISSIONS VALUES (300,300);

INSERT INTO USER_LOGIN VALUES (200,'SEED',NOW(),1,NULL,NULL,0,'la','la',1,'libraryPanel','1');

INSERT INTO USER_LOGIN VALUES (300,'SEED',NOW(),1,NULL,NULL,0,'member','member',1,'bookListForMember','1');

INSERT INTO USERLOGIN_SECURITY_GROUPS VALUES (200,200);

INSERT INTO USERLOGIN_SECURITY_GROUPS VALUES (300,300);

insert into HOME_PAGE_DETAILS values (200,'SEED',NOW(),1,NULL,NULL,0,'Library Management Administrator Home Page','libraryPanel');

insert into HOME_PAGE_DETAILS values (300,'SEED',NOW(),1,NULL,NULL,0,'Library Management Member Home Page','bookListForMember');

ALTER TABLE MEMBER ADD UNIQUE (MEMBER_ID);

ALTER TABLE BOOK ADD UNIQUE (ISBN);