INSERT INTO SECURITY_PERMISSION VALUES (200,'SEED',NOW(),0,NULL,NULL,0,'Permission for Library Admin','ROLE_LIBADMIN');

INSERT INTO SECURITY_GROUP VALUES(200,'SEED',NOW(),0,NULL,NULL,0,'LIBADMIN','1');

INSERT INTO SECURITYGROUP_SECURITY_PERMISSIONS VALUES (200,200);

INSERT INTO USER_LOGIN VALUES (200,'SEED',NOW(),1,NULL,NULL,0,'la','la',1,'libraryPanel','1');

INSERT INTO USERLOGIN_SECURITY_GROUPS VALUES (200,200);

insert into HOME_PAGE_DETAILS values (200,'SEED',NOW(),1,NULL,NULL,0,'Library Management Administrator Home Page','libraryPanel');

ALTER TABLE MEMBER ADD UNIQUE (MEMBER_ID);

ALTER TABLE BOOK ADD UNIQUE (ISBN);