DELETE FROM USERLOGIN_SECURITY_GROUPS;

DELETE FROM SECURITYGROUP_SECURITY_PERMISSIONS;

DELETE FROM SECURITY_PERMISSION;

DELETE FROM SECURITY_GROUP;

DELETE FROM USER_LOGIN;

DELETE FROM USERLOGIN_SECURITY_GROUPS;

DELETE FROM SECURITYGROUP_SECURITY_PERMISSIONS;

DELETE FROM SECURITY_PERMISSION;

DELETE FROM SECURITY_GROUP;

DELETE FROM USER_LOGIN;

DELETE FROM HOME_PAGE_DETAILS;

INSERT INTO SECURITY_PERMISSION VALUES (1,'SEED','2011-11-07 12:01:52',0,NULL,NULL,0,'Permission for Super Admin','ROLE_SUPERADMIN');

INSERT INTO SECURITY_GROUP VALUES(1,'SEED','2011-11-07 13:51:34',0,NULL,NULL,0,'SUPERADMIN','1');

INSERT INTO SECURITYGROUP_SECURITY_PERMISSIONS VALUES (1,1);

INSERT INTO USER_LOGIN VALUES (1,'SEED','2011-11-07 13:54:32',1,NULL,NULL,0,'sa','sa',1,'personPanel','1');

INSERT INTO USERLOGIN_SECURITY_GROUPS VALUES (1,1);

INSERT INTO HOME_PAGE_DETAILS VALUES (1,'SEED','2011-11-07 13:54:32',1,NULL,NULL,0,'Superadmin Home Page','personPanel1');
